apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-kafka2db
  name: udaconnect-locations-kafka2db
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        service: udaconnect-locations-kafka2db
    spec:
      containers:
      - image: moebius5/nd064-udaconnect-locations-kafka2db:latest
        name: udaconnect-locations-kafka2db
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
